##################################################################
#                           BasherMine                           #
##################################################################
#
# Автор: Aleks_Basher
# Telegram: https://t.me/aleks_basher
#
# Команды:
#   /bashermine - админ-команды
# Права:
#   bashermine.command.bashermine - доступ к /bashermine
#
hologram:
  lines:
    - '&e⚒ Авто-Шахта ⚒'
    - '&fТекущая: {current}'
    - '&fСледующая: {next}'
    - '&fОбновление через:'
    - '&6{time}'